server:
  port: 8080
spring:
  application:
    name: api-service
  http:
    client:
      service:
        read-timeout: 8888ms
        default-header:
          -test2: test2
        group:
          -default: # default group (no load balancing)
            base-url: http://localhost:8083
            connect-timeout:
              nanos: 6666
            default-header:
              -test: test
          -company-service:
            base-url: http://company-service
            read-timeout: # override default
              nanos: 9999
          -employee-service:
            # baseUrl resolved by LoadBalancer
            -default-header:
              -test: test
  cloud:
    compatibility-verifier:
      enabled: false
    discovery:
      client:
        simple:
          instances:
            company-service:
              - uri: http://localhost:8081
            employee-service:
              - uri: http://localhost:8082
            person-service:
              - uri: http://localhost:8083
